In [13]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

In [4]:
data=pd.read_csv(r'C:\Users\DELL\Desktop\CODSOFT DATA ANALYTICS\codsoft_DA.csv')

In [9]:
#basic inspection
data.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Product,Category,Quantity,Unit_Price,Revenue,City,Payment_Method,Order_Status,Customer_Age,Sales_Channel
0,ORD0362,4/25/2025,C1081,Priya,PRINTER,Office,2,9999,19998,Delhi,UPI,completed,44,Online
1,ORD0074,2/6/2025,C1019,NaN,keyboard,accessories,3,999,2997,Ahmedabad,Net Banking,Cancelled,46,Online
2,ORD0375,6/15/2025,C1144,Vikram,usb cable,NaN,4,499,1996,Chennai,UPI,completed,42,store
3,ORD0156,6/13/2025,C1203,Rahul,USB Cable,Accessories,7,299,2093,Kolkata,Debit Card,PENDING,65,Store
4,ORD0105,2/1/2025,C1243,Anjali,Tablet,Electronics,5,9999,49995,Hyderabad,Net Banking,Completed,21,online

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        500 non-null    str
 1   Order_Date      495 non-null    str
 2   Customer_ID     500 non-null    str
 3   Customer_Name   485 non-null    str
 4   Product         500 non-null    str
 5   Category        492 non-null    str
 6   Quantity        485 non-null    str
 7   Unit_Price      492 non-null    str
 8   Revenue         491 non-null    str
 9   City            485 non-null    str
 10  Payment_Method  489 non-null    str
 11  Order_Status    500 non-null    str
 12  Customer_Age    482 non-null    str
 13  Sales_Channel   500 non-null    str
dtypes: str(14)
memory usage: 95.8 KB

In [8]:
print("Number of Rows:", data.shape[0])
print("Number of Columns:",data.shape[1])

Number of Rows: 500
Number of Columns: 14

In [12]:
data.describe(include='all')

,Order_ID,Order_Date,Customer_ID,Customer_Name,Product,Category,Quantity,Unit_Price,Revenue,City,Payment_Method,Order_Status,Customer_Age,Sales_Channel
count,500,495,500,485,500,492,485,492,491,485,489,500,482,500
unique,470,181,212,12,30,6,14,32,192,10,5,7,53,5
top,ORD0276,4/5/2025,C1103,Amit,Keyboard,Accessories,3,999,4497,Hyderabad,Cash,completed,46,store
freq,3,10,6,51,40,171,73,41,7,58,102,80,19,111

In [14]:
#finding missing values
data.isnull().sum()
print(data)

    Order_ID Order_Date Customer_ID Customer_Name    Product     Category  \
0    ORD0362  4/25/2025       C1081         Priya    PRINTER       Office
1    ORD0074   2/6/2025       C1019           NaN   keyboard  accessories
2    ORD0375  6/15/2025       C1144        Vikram  usb cable          NaN
3    ORD0156  6/13/2025       C1203         Rahul  USB Cable  Accessories
4    ORD0105   2/1/2025       C1243        Anjali     Tablet  Electronics
..       ...        ...         ...           ...        ...          ...
495  ORD0107   2/3/2025       C1139         Rohit     laptop  Electronics
496  ORD0271   1/7/2025       C1218         Arjun   Keyboard  Accessories
497  ORD0349  1/26/2025       C1170         Karan      Mouse  Accessories
498  ORD0436   2/8/2025       C1122         Rahul   keyboard  accessories
499  ORD0103   2/9/2025       C1227        Vikram    Monitor  electronics

    Quantity Unit_Price Revenue       City Payment_Method Order_Status  \
0          2       9999   19998      Delhi            UPI    completed
1          3        999    2997  Ahmedabad    Net Banking    Cancelled
2          4        499    1996    Chennai            UPI    completed
3          7        299    2093    Kolkata     Debit Card      PENDING
4          5       9999   49995  Hyderabad    Net Banking    Completed
..       ...        ...     ...        ...            ...          ...
495        5      52000  260000      Delhi    Credit Card    Completed
496        5       1499    7495    Lucknow    Net Banking      PENDING
497        7        999    6993  Ahmedabad    Credit Card    completed
498        3       1499    4497     Jaipur    Credit Card     COMPLETE
499        7      18999  132993  Ahmedabad           Cash    Cancelled

    Customer_Age Sales_Channel
0             44        Online
1             46        Online
2             42         store
3             65         Store
4             21        online
..           ...           ...
495           40         Store
496           30         store
497           24        ONLINE
498           58        ONLINE
499           20        online

[500 rows x 14 columns]

In [15]:
#finding Duplicates
print("number of duplicate rows:",
      data.duplicated().sum())

number of duplicate rows: 19

In [16]:
#checking unique values
for column in data.select_dtypes(include='object').columns:
    print("\n", column)
    print(data[column].dropna().unique()[:30])

 Order_ID
<ArrowStringArray>
['ORD0362', 'ORD0074', 'ORD0375', 'ORD0156', 'ORD0105', 'ORD0395', 'ORD0378',
 'ORD0125', 'ORD0069', 'ORD0451', 'ORD0010', 'ORD0195', 'ORD0407', 'ORD0085',
 'ORD0372', 'ORD0389', 'ORD0433', 'ORD0231', 'ORD0317', 'ORD0409', 'ORD0390',
 'ORD0033', 'ORD0281', 'ORD0357', 'ORD0077', 'ORD0462', 'ORD0212', 'ORD0102',
 'ORD0335', 'ORD0476']
Length: 30, dtype: str

 Order_Date
<ArrowStringArray>
[ '4/25/2025',   '2/6/2025',  '6/15/2025',  '6/13/2025',   '2/1/2025',
   '1/2/2025',   '3/9/2025', '13/06/2025',  '6/11/2025',  '6/16/2025',
   '5/7/2025',   '4/9/2025',  '5/27/2025',  '3/30/2025',  '1/30/2025',
  '2/10/2025',  '5/29/2025',  '1/12/2025',  '5/25/2025',  '2/12/2025',
  '5/22/2025',  '3/20/2025',  '2/27/2025',   '4/8/2025',  '2/16/2025',
  '5/26/2025',  '1/21/2025',  '1/10/2025',  '3/23/2025',  '2/11/2025']
Length: 30, dtype: str

 Customer_ID
<ArrowStringArray>
['C1081', 'C1019', 'C1144', 'C1203', 'C1243', 'C1034', 'C1107', 'C1176',
 'C1191', 'C1024', 'C1061', 'C1038', 'C1086', 'C1195', 'C1137', 'C1026',
 'C1001', 'C1016', 'C1186', 'C1224', 'C1094', 'C1083', 'C1200', 'C1150',
 'C1048', 'C1237', 'C1078', 'C1175', 'C1103', 'C1225']
Length: 30, dtype: str

 Customer_Name
<ArrowStringArray>
[ 'Priya', 'Vikram',  'Rahul', 'Anjali',   'Amit',  'Rohit',  'Karan',
   'Neha',  'Sneha',  'Arjun',  'Pooja',  'Meera']
Length: 12, dtype: str

 Product
<ArrowStringArray>
[   'PRINTER',   'keyboard',  'usb cable',  'USB Cable',     'Tablet',
    'monitor',    'printer',     'Webcam',   'Keyboard', 'headphones',
 'HEADPHONES',     'WEBCAM',     'tablet',     'Laptop', 'smartphone',
      'Mouse', 'Headphones',      'mouse',    'Printer', 'Smartphone',
     'webcam',    'Monitor',     'TABLET',    'MONITOR',  'USB CABLE',
      'MOUSE', 'SMARTPHONE',     'laptop',   'KEYBOARD',     'LAPTOP']
Length: 30, dtype: str

 Category
<ArrowStringArray>
['Office', 'accessories', 'Accessories', 'Electronics', 'electronics',
 'office']
Length: 6, dtype: str

 Quantity
<ArrowStringArray>
['2', '3', '4', '7', '5', '1', '8', '6', '200', '100', '60', '75', '50',
 'five']
Length: 14, dtype: str

 Unit_Price
<ArrowStringArray>
[   '9999',     '999',     '499',     '299',    '8999',   '24999',   '14999',
    '1999',    '1499',    '3999',    '2999',   '15999',   '72000',   '25000',
     '599',    '2499',     '399',   '12000',    '1299',     '199',   '12999',
   '18999',   '35000', 'unknown',     '699',  '45,000',   '45000',    '6999',
   '65000',   '18000']
Length: 30, dtype: str

 Revenue
<ArrowStringArray>
[ '19998',   '2997',   '1996',   '2093',  '49995',  '62993', '124995',
 '174993',  '29998',   '9995',   '4497',    '999',  '31992',  '17994',
  '15999', '288000', '175000',   '2396',   '7497',   '2394',  '29997',
   '3999',  '44997',  '15992',   '3192',   '8994',  '36000',   '3493',
   '1995',   '6495']
Length: 30, dtype: str

 City
<ArrowStringArray>
[    'Delhi', 'Ahmedabad',   'Chennai',   'Kolkata', 'Hyderabad',      'Pune',
 'Bangalore',    'Jaipur',   'Lucknow',    'Mumbai']
Length: 10, dtype: str

 Payment_Method
<ArrowStringArray>
['UPI', 'Net Banking', 'Debit Card', 'Cash', 'Credit Card']
Length: 5, dtype: str

 Order_Status
<ArrowStringArray>
['completed', 'Cancelled',   'PENDING', 'Completed',  'COMPLETE', 'cancelled',
   'Pending']
Length: 7, dtype: str

 Customer_Age
<ArrowStringArray>
[ '44',  '46',  '42',  '65',  '21',  '41',  '27',  '57',  '33',  '26',  '22',
  '54',  '56',  '58',  '34',  '55',  '32',  '25',  '39',  '35',  '48',  '59',
  '52',  '23',  '47',  '45',  '63',  '31', '120',  '18']
Length: 30, dtype: str

 Sales_Channel
<ArrowStringArray>
['Online', 'store', 'Store', 'online', 'ONLINE']
Length: 5, dtype: str

C:\Users\DELL\AppData\Local\Temp\ipykernel_16580\1420209192.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for column in data.select_dtypes(include='object').columns:

In [18]:
#clean spaces
for column in data.select_dtypes(include=['object', 'string']).columns:
    data[column] = data[column].str.strip()

In [21]:
#standardize product name
data['Product']
data['Product'].str.title()

0        Printer
1       Keyboard
2      Usb Cable
3      Usb Cable
4         Tablet
         ...
495       Laptop
496     Keyboard
497        Mouse
498     Keyboard
499      Monitor
Name: Product, Length: 500, dtype: str

In [22]:
#standardize categories
data['Category']
data['Category'].str.title()

0           Office
1      Accessories
2              NaN
3      Accessories
4      Electronics
          ...
495    Electronics
496    Accessories
497    Accessories
498    Accessories
499    Electronics
Name: Category, Length: 500, dtype: str

In [23]:
#standardize sales channel
data['Sales_Channel']
data['Sales_Channel'].str.title()

0      Online
1      Online
2       Store
3       Store
4      Online
        ...
495     Store
496     Store
497    Online
498    Online
499    Online
Name: Sales_Channel, Length: 500, dtype: str

In [24]:
#standardize order status
data['Order_Status'] = data['Order_Status'].str.strip().str.lower()

data['Order_Status'] = data['Order_Status'].replace({
    'complete': 'Completed',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'pending': 'Pending'
})

data['Order_Status'].value_counts()

Order_Status
Completed    226
Cancelled    141
Pending      133
Name: count, dtype: int64

In [25]:
#convert Date
data['Order_Date'] = pd.to_datetime(
    data['Order_Date'],
    errors='coerce'
)

In [26]:
print("Invalid/Missing Dates:", data['Order_Date'].isna().sum())

Invalid/Missing Dates: 13

In [27]:
#clean Quantity
data['Quantity'] = data['Quantity'].replace({
    'five': '5'
})

data['Quantity'] = pd.to_numeric(
    data['Quantity'],
    errors='coerce'
)

In [28]:
#clean unit price
def clean_price(value):
    if pd.isna(value):
        return np.nan
    
    value = str(value).strip().lower().replace(',', '')
    
    if value == 'unknown':
        return np.nan
    
    if value.endswith('k'):
        return float(value[:-1]) * 1000
    
    try:
        return float(value)
    except:
        return np.nan

data['Unit_Price'] = data['Unit_Price'].apply(clean_price)

In [29]:
data['Unit_Price'].head(20)

0      9999.0
1       999.0
2       499.0
3       299.0
4      9999.0
5      8999.0
6     24999.0
7     24999.0
8     14999.0
9      1999.0
10     1499.0
11      999.0
12      999.0
13     3999.0
14     2999.0
15    15999.0
16    72000.0
17    25000.0
18      599.0
19     2499.0
Name: Unit_Price, dtype: float64

In [30]:
#clean Revenue
data['Revenue'] = pd.to_numeric(
    data['Revenue'],
    errors='coerce'
)

In [31]:
#clean Customer Age
data['Customer_Age'] = pd.to_numeric(
    data['Customer_Age'],
    errors='coerce'
)

In [33]:
#Handling missing values

#For Categorial columns
categorical_columns = [
    'Customer_Name',
    'Category',
    'City',
    'Payment_Method'
]

for column in categorical_columns:
    data[column] = data[column].fillna('Unknown')

#For numerical columns
numerical_columns = [
    'Quantity',
    'Unit_Price',
    'Revenue',
    'Customer_Age'
]

for column in numerical_columns:
    data[column] = data[column].fillna(data[column].median())

#For Date
data['Order_Date'] = data['Order_Date'].fillna(
    data['Order_Date'].mode()[0]
)

In [34]:
#Remove Duplicates
data = data.drop_duplicates()

print("Rows after removing duplicates:", len(data))

Rows after removing duplicates: 481

In [35]:
#Check Final Dataset
print("Missing values:")
print(data.isnull().sum())

print("\nDuplicate rows:")
print(data.duplicated().sum())

Missing values:
Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Product           0
Category          0
Quantity          0
Unit_Price        0
Revenue           0
City              0
Payment_Method    0
Order_Status      0
Customer_Age      0
Sales_Channel     0
dtype: int64

Duplicate rows:
0

In [36]:
#Verify Datatypes
data.dtypes

Order_ID                     str
Order_Date        datetime64[us]
Customer_ID                  str
Customer_Name                str
Product                      str
Category                     str
Quantity                 float64
Unit_Price               float64
Revenue                  float64
City                         str
Payment_Method               str
Order_Status                 str
Customer_Age             float64
Sales_Channel                str
dtype: object

In [38]:
#Save Cleaned Dataset
data.to_csv(
    "cleaned_sales_data.csv",
    index=False
)

## Task 1 Conclusion

The dataset was successfully imported and inspected using Pandas. Missing values, duplicate records, inconsistent categorical values, invalid numerical values, and incorrect data types were identified and handled. The cleaned dataset was prepared for further analysis and exported as a CSV file.